### ISSUE TITLE
Self-hosting models like OLLAMA support

### ISSUE THREAD

**Issue by justalike** [AmberSahdev/Open-Interface#7]
It would be really awesome for mass-consumer if anyone could host his own models like GPT4V (if such exists).
I'm not familiar if such do exist, but I bet lots of self-hosting devs would be so grateful for such feature.

**Comment by AmberSahdev** [comment]
Hey yeah there are a couple of options available for that like Llava. I've added the instructions in the readme now on how to configure that - https://github.com/AmberSahdev/Open-Interface?tab=readme-ov-file#setup

**Comment by AmberSahdev** [comment]
Aah I should mention this in the readme somewhere because it took me a little to find the right URL as well - it's `http://localhost:11434/v1` 


<img width="291" alt="Screenshot 2024-05-22 at 12 02 12 PM" src="https://github.com/AmberSahdev/Open-Interface/assets/23853621/a25a675b-4ef9-46ae-b949-cce7766812a7">

**Comment by toonvank** [comment]
I get this response when entering the data, ollama is running at default port and llava:latest should be installed
![image](https://github.com/AmberSahdev/Open-Interface/assets/61182641/b63029c9-4d9f-480f-86fc-88a10f6a8c4a)

**Comment by PersusUS** [comment]
i am having this same issue
